# Generated by Django 5.0.7 on 2024-07-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/pic/default_post_img.png', upload_to='blog/posts/'),
        ),
    ]
