# Generated by Django 5.0.7 on 2024-08-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, default='img/user/avatar.jpg', upload_to='users'),
        ),
    ]
