# Generated by Django 5.0.4 on 2024-08-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('student', 'student'), ('head', 'head'), ('admin', 'admin')], default=('student', 'student'), max_length=10),
        ),
    ]
