# Generated by Django 4.2 on 2024-10-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_website',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
