# Generated by Django 5.0.4 on 2024-08-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='published_at_detail',
            field=models.CharField(default='test', max_length=512),
        ),
    ]
