# Generated by Django 5.0.4 on 2024-08-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publication_published_at_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='publications/'),
        ),
    ]
